[2023-09-11T08:19:25.323+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mlb_parser.create_postgre_table manual__2023-09-11T08:19:22.736921+00:00 [queued]>
[2023-09-11T08:19:25.403+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mlb_parser.create_postgre_table manual__2023-09-11T08:19:22.736921+00:00 [queued]>
[2023-09-11T08:19:25.410+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-09-11T08:19:25.453+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgre_table> on 2023-09-11 08:19:22.736921+00:00
[2023-09-11T08:19:25.472+0000] {standard_task_runner.py:57} INFO - Started process 25325 to run task
[2023-09-11T08:19:25.505+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'mlb_parser', 'create_postgre_table', 'manual__2023-09-11T08:19:22.736921+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/mlb_parser.py', '--cfg-path', '/tmp/tmpg2r4j01d']
[2023-09-11T08:19:25.761+0000] {standard_task_runner.py:85} INFO - Job 382: Subtask create_postgre_table
[2023-09-11T08:19:31.029+0000] {task_command.py:415} INFO - Running <TaskInstance: mlb_parser.create_postgre_table manual__2023-09-11T08:19:22.736921+00:00 [running]> on host 2e8147b3a465
[2023-09-11T08:19:31.084+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='andy_hsu' AIRFLOW_CTX_DAG_ID='mlb_parser' AIRFLOW_CTX_TASK_ID='create_postgre_table' AIRFLOW_CTX_EXECUTION_DATE='2023-09-11T08:19:22.736921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-09-11T08:19:22.736921+00:00'
[2023-09-11T08:19:31.087+0000] {sql.py:274} INFO - Executing: 
            create table if not exists mlb_parser (
                Name varchar(40),
                POS varchar(5),
                Team varchar(20),
                G int,
                AB int,
                R int,
                H int,
                Double int,
                Third int,
                HR int,
                RBI int,
                BB int,
                SO int,
                SB int,
                CS int, 
                OBP float,
                SLG float,
                primary key(Name, POS, Team)
            )
            
[2023-09-11T08:19:31.093+0000] {base.py:73} INFO - Using connection ID 'postgres_mlb_parser' for task execution.
[2023-09-11T08:19:31.107+0000] {base.py:73} INFO - Using connection ID 'postgres_mlb_parser' for task execution.
[2023-09-11T08:19:31.141+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 154, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "host.docker.internal" (192.168.65.2), port 5432 failed: FATAL:  database "mlb_parser_DB" does not exist

[2023-09-11T08:19:31.155+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=mlb_parser, task_id=create_postgre_table, execution_date=20230911T081922, start_date=20230911T081925, end_date=20230911T081931
[2023-09-11T08:19:31.163+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 382 for task create_postgre_table (connection to server at "host.docker.internal" (192.168.65.2), port 5432 failed: FATAL:  database "mlb_parser_DB" does not exist
; 25325)
[2023-09-11T08:19:31.187+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-09-11T08:19:31.198+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
